apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-jenkines-docker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pipeline-jenkines-docker
  template:
    metadata:
      labels:
        app: pipeline-jenkines-docker
    spec:
      containers:
        - name: pipeline-jenkines-docker
          image: pipeline-jenkines-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-jenkines-docker-service
spec:
  selector:
    app: pipeline-jenkines-docker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort